services:
  backend:
    image: gradle:jdk21
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    command:
      ["tail", "-f", "/dev/null"]
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${LOCAL_DB_USER}
      MYSQL_PASSWORD: ${USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
