spring:
  cloud:
    aws:
      credentials:
        #access-key: ${ACCESS_KEY}
        #secret-key: ${SECRET_KEY}
      region:
        #static: ap-northeast-2  # 버킷의 리전
      s3:
        #bucket: growlog-travel-service   # 버킷 이름
      stack:
        auto: false