spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    #include: s3
  config:
    import: optional:file:.env[.properties]


springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI ?? ??: http://localhost:8080/swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs  # OpenAPI ?? ??
