spring:
  datasource:
    url: jdbc:mysql://localhost:3306/{LOCAL_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${ROOT_PASSWORD}

  jpa:
    database: mysql
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect