spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    include: s3 # prod일 때만 s3 프로파일 포함시켜야 하기 때문에 주석처리
  config:
    import: optional:file:.env[.properties]


springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI ?? ??: http://localhost:8080/swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs  # OpenAPI ?? ??

docker:
  workspace-path: /app

liveblocks:
  secret-key: ${LIVEBLOCKS_SECRET_KEY}
  salt: ${LIVEBLOCKS_ROOM_SALT}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
