spring:
  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      region:
        static: ${S3_REGION}  # 버킷의 리전
      s3:
        bucket: ${S3_BUCKET_NAME}   # 버킷 이름
      stack:
        auto: false
