name: Jira 연동 이슈 생성
description: 이 템플릿을 기반으로 Jira 이슈가 자동으로 생성됩니다.
# [수정됨] JIRA-KEY 부분을 제거하여 사용자가 제목만 입력하도록 유도
title: "이슈 제목을 작성해주세요"
labels: [ "feature" ] # 기본으로 붙일 GitHub 레이블
assignees: [ ]

body:
  - type: dropdown
    id: issue_type
    attributes:
      label: "이슈 유형"
      description: "생성할 Jira 이슈의 유형을 선택해주세요."
      options:
        - Task
        - Bug
        - Story
        - Sub-task
    validations:
      required: true

  - type: input
    id: epic_number
    attributes:
      label: "상위 에픽 이슈 키"
      description: "연결할 상위 Jira 에픽이 있다면 이슈 키를 작성해주세요. (선택 사항)"
      placeholder: "예: PROJ-123"

  # [수정됨] options의 문법을 올바르게 변경
  - type: dropdown
    id: issue_label
    attributes:
      label: "GitHub 레이블 추가"
      description: "이 GitHub 이슈에 추가할 레이블을 선택해주세요. (선택 사항)"
      multiple: true # 여러 개 선택 가능하도록 설정
      options:
        - frontend
        - backend
        - infra
        - urgent
        - 논의필요
        - 개선필요
    validations:
      required: false

  - type: textarea
    id: issue_description
    attributes:
      label: "이슈 상세 설명"
      description: "Jira에 등록될 상세 설명을 작성해주세요."
      placeholder: "사용자가 로그인 시 필요한 인증 기능을 제공하여 보안과 사용자 세션을 관리합니다."
    validations:
      required: true

  - type: textarea
    id: task_list
    attributes:
      label: 작업 목록 (체크리스트)
      description: |
        작업 항목을 직접 작성해주세요. 줄바꿈으로 구분되며, Jira 이슈의 checklist로 포함됩니다.
      placeholder: |
        예)
        /api/login 엔드포인트 개발
        이메일 및 비밀번호 검증 로직 구현
        JWT 토큰 발급 및 응답 처리
