name: Web IDE Backend CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]  # main 또는 develop 브랜치로의 PR 생성/수정 시 실행됨

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub 제공 우분투 환경에서 실행

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: webide
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DB_HOST: 127.0.0.1
      DB_NAME: webide
      DB_USER_NAME: root
      DB_USER_PASSWORD: root


    steps:
      # 1. GitHub 코드 체크아웃
      - name: 🔄 Checkout source code
        uses: actions/checkout@v3  # PR 브랜치의 소스코드를 가져옴

      # 2. JDK 21 설치
      - name: ☕ JDK 21 설치
        uses: actions/setup-java@v3
        with:
          java-version: '21'       # 프로젝트에서 사용하는 Java 버전
          distribution: 'temurin'  # Temurin은 OpenJDK 배포판 중 하나

      - name: 📄 Create .env file for CI
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_NAME=webide" >> .env
          echo "DB_USER_NAME=root" >> .env
          echo "DB_USER_PASSWORD=root" >> .env
          echo "JWT_SECRET=mytestsecret" >> .env
          echo "JWT_EXPIRATION=3600000" >> .env
          echo "SPRING_PROFILES_ACTIVE=local" >> .env
          echo "MAIL_USERNAME=test@example.com" >> .env
          echo "MAIL_PASSWORD=secret" >> .env
          echo "MAIL_FROM=test@example.com" >> .env

      - name: ⏳ Wait for MySQL to be healthy
        run: |
            for i in {1..10}; do
              nc -z 127.0.0.1 3306 && echo "MySQL is up!" && exit 0
              echo "Waiting for MySQL..."
              sleep 3
            done
            echo "MySQL did not start in time" && exit 1

      # 3. Gradle 빌드 및 테스트 실행
      - name: 🧪 Gradle Build & Test
        run: ./gradlew build       # compile, test 등 전체 빌드 수행
